const makeInitialState = ({ videoId, topic = "", angle = "", selectedIdea = null }) => {
  const now = new Date().toISOString();
  return {
    video_id: videoId,
    idea_id: null,
    topic,
    angle,
    status: "initialized",
    current_step: "initialized",
    approved: false,
    selected_idea: selectedIdea,
    ideas: [],
    research_json: {},
    outline_json: {},
    script_text: "",
    script_path: "",
    visual_plan: [],
    audio_path: "",
    duration_seconds: 0,
    caption_path_srt: "",
    caption_path_vtt: "",
    assets_json: {
      visual_keywords: [],
      search_queries: [],
      items: [],
      fallback_plan: [],
      missing_assets: false,
      last_refresh_scene_indexes: [],
      last_refresh_reason: "",
      last_refreshed_at: "",
    },
    render_path: "",
    thumbnail_path: "",
    review: {
      draft_version: 1,
      last_rejection_note: "",
      last_rejected_at: "",
      last_published_at: "",
      last_refreshed_scene_indexes: [],
      last_refresh_reason: "",
      last_refreshed_at: "",
      drive_file_id: "",
      drive_view_url: "",
      drive_download_url: "",
      sheet_url: "",
      sheet_name: "",
    },
    youtube_title: "",
    youtube_description: "",
    youtube_tags: [],
    youtube_chapters: [],
    youtube_video_id: "",
    youtube_url: "",
    youtube_privacy_status: "",
    youtube_caption_track_id: "",
    youtube_caption_language: "",
    youtube_caption_format: "",
    youtube_caption_status: "",
    youtube_caption_error_message: "",
    render_timeline: {
      strategy: "",
      transition: "",
      output_resolution: "",
      output_duration_seconds: 0,
      total_clips: 0,
      unique_asset_count: 0,
      semantic_alignment_score_average: 0,
      low_confidence_clip_count: 0,
      clips: [],
    },
    telegram: {
      chat_id: "",
      ideas_message_id: null,
      ideas_message_sent_at: "",
      final_review_message_id: null,
      final_review_version: null,
      final_review_message_sent_at: "",
      last_inbound_message_id: null,
      last_inbound_text: "",
      last_inbound_at: "",
      sent_status_keys: [],
    },
    error_message: "",
    state_path: "",
    created_at: now,
    updated_at: now,
  };
};

module.exports = { makeInitialState };