const makeInitialState = ({ videoId, topic = "", angle = "", selectedIdea = null }) => {
  const now = new Date().toISOString();
  return {
    video_id: videoId,
    idea_id: null,
    topic,
    angle,
    status: "initialized",
    current_step: "initialized",
    approved: false,
    selected_idea: selectedIdea,
    ideas: [],
    research_json: {},
    outline_json: {},
    script_text: "",
    script_path: "",
    script_provider: "",
    script_fallback_used: false,
    visual_plan: [],
    audio_path: "",
    tts_primary_provider: "multivozes",
    tts_effective_provider: "",
    tts_fallback_used: false,
    tts_error_class: "",
    duration_seconds: 0,
    audio_intelligence_path: "",
    audio_intelligence_provider: "",
    scene_boundaries: [],
    chapter_triggers: [],
    caption_path_srt: "",
    caption_path_vtt: "",
    assets_json: {
      visual_keywords: [],
      search_queries: [],
      retrieval_budget: [],
      raw_items: [],
      approved_items: [],
      approved_windows: [],
      rejected_windows: [],
      block_packages: [],
      slot_query_plan: [],
      micro_visual_plan: [],
      slot_coverage_by_block: [],
      block_coverage_by_block: [],
      block_coverage_summary: {},
      block_repair_states: [],
      local_repair_plan: {
        generated_at: "",
        max_repair_rounds: 0,
        block_states: [],
        repair_by_scene: [],
        repair_outcomes: [],
        scene_indexes_to_refresh: [],
        blocked_scene_indexes: [],
        summary: {},
      },
      micro_coverage_by_scene: [],
      micro_coverage_gaps: [],
      block_candidate_funnel: [],
      editorial_asset_library_snapshot: {},
      retention_learning: {
        updated_at: "",
        observations_count: 0,
        provider_retention_snapshot: {},
      },
      editorial_bins_by_scene: {},
      editorial_metrics: {},
      scene_editorial_readiness: [],
      provider_reliability: {},
      clip_library: {
        enabled: false,
        policy_version: "v1",
        generated_clip_ids: [],
        approved_clip_ids: [],
        clips_generated: 0,
        clips_approved: 0,
        clip_reuse_ratio: 0,
        last_indexed_at: "",
        last_shadow_report_path: "",
      },
      items: [],
      fallback_plan: [],
      missing_assets: false,
      blocking_scene_indexes: [],
      scene_asset_readiness: [],
      last_repair_plan_by_scene: [],
      last_refresh_scene_indexes: [],
      last_refresh_reason: "",
      last_refreshed_at: "",
    },
    render_path: "",
    thumbnail_path: "",
    review: {
      draft_version: 1,
      last_rejection_note: "",
      last_rejected_at: "",
      last_published_at: "",
      last_refreshed_scene_indexes: [],
      last_refresh_reason: "",
      last_refreshed_at: "",
      drive_file_id: "",
      drive_view_url: "",
      drive_download_url: "",
      sheet_url: "",
      sheet_name: "",
    },
    youtube_title: "",
    youtube_description: "",
    youtube_tags: [],
    youtube_chapters: [],
    youtube_video_id: "",
    youtube_url: "",
    youtube_privacy_status: "",
    youtube_caption_track_id: "",
    youtube_caption_language: "",
    youtube_caption_format: "",
    youtube_caption_status: "",
    youtube_caption_error_message: "",
    render_timeline: {
      strategy: "",
      transition: "",
      output_resolution: "",
      output_duration_seconds: 0,
      total_clips: 0,
      unique_asset_count: 0,
      semantic_alignment_score_average: 0,
      low_confidence_clip_count: 0,
      micro_sync_metrics: {},
      clips: [],
    },
    render_validation: {
      is_publishable: false,
      needs_regeneration: false,
      needs_manual_review: false,
      quality_score: 0,
      alignment_score: 0,
      diversity_score: 0,
      technical_score: 0,
      hard_boundary_status: "unknown",
      max_visual_lag_sec: 0,
      hard_boundary_report: {
        status: "unknown",
        max_visual_lag_sec: 0,
        avg_visual_lag_sec: 0,
        boundaries: [],
        violations: [],
      },
      editorial_metrics: {},
      qa_profile: "strict",
      qa_runtime_profile: "prod_strict",
      editorial_failure_codes: [],
      publish_blocked: false,
      publish_blocked_codes: [],
      provider_reliability: {},
      regeneration_plan: {
        scene_indexes_to_refresh: [],
        failure_codes: [],
        repair_by_scene: [],
      },
      editorial_observability: {},
      critical_slot_audit: [],
      issues: [],
      scene_indexes_to_refresh: [],
      clip_indexes_to_replace: [],
    },
    editorial_observability_history: [],
    local_library_min_score_fallback_reasons: [],
    clip_library_summary: {
      clips_generated: 0,
      clips_approved: 0,
      clip_reuse_ratio: 0,
      generated_clip_ids: [],
      approved_clip_ids: [],
      last_updated_at: "",
    },
    telegram: {
      chat_id: "",
      ideas_message_id: null,
      ideas_message_sent_at: "",
      final_review_message_id: null,
      final_review_version: null,
      final_review_message_sent_at: "",
      last_inbound_message_id: null,
      last_inbound_text: "",
      last_inbound_at: "",
      sent_status_keys: [],
    },
    error_message: "",
    external_api_stats: {
      total_calls: 0,
      openai_calls: 0,
      gemini_calls: 0,
      youtube_calls: 0,
      blocked_calls: 0,
      fallbacks_used: 0,
      last_updated_at: "",
    },
    state_path: "",
    created_at: now,
    updated_at: now,
  };
};

module.exports = { makeInitialState };
